# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models, migrations
from django.conf import settings


class Migration(migrations.Migration):

    dependencies = [
        ('digidemo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'verbose_name': 'answer', 'verbose_name_plural': 'answers'},
        ),
        migrations.AlterModelOptions(
            name='answercomment',
            options={'verbose_name': 'comment', 'verbose_name_plural': 'comments'},
        ),
        migrations.AlterModelOptions(
            name='answervote',
            options={'verbose_name': 'vote', 'verbose_name_plural': 'vote'},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': 'comment', 'verbose_name_plural': 'comments'},
        ),
        migrations.AlterModelOptions(
            name='commentvote',
            options={'verbose_name': 'vote', 'verbose_name_plural': 'vote'},
        ),
        migrations.AlterModelOptions(
            name='discussion',
            options={'verbose_name': 'discussion', 'verbose_name_plural': 'discussions'},
        ),
        migrations.AlterModelOptions(
            name='discussioncomment',
            options={'verbose_name': 'comment', 'verbose_name_plural': 'comments'},
        ),
        migrations.AlterModelOptions(
            name='discussionvote',
            options={'verbose_name': 'vote', 'verbose_name_plural': 'vote'},
        ),
        migrations.AlterModelOptions(
            name='emailrecipient',
            options={'verbose_name': 'user on our email list', 'verbose_name_plural': 'users on our email list'},
        ),
        migrations.AlterModelOptions(
            name='emailverification',
            options={'verbose_name': 'email verification', 'verbose_name_plural': 'email verifications'},
        ),
        migrations.AlterModelOptions(
            name='letter',
            options={'verbose_name': 'letter', 'verbose_name_plural': 'letters'},
        ),
        migrations.AlterModelOptions(
            name='lettervote',
            options={'verbose_name': 'vote', 'verbose_name_plural': 'vote'},
        ),
        migrations.AlterModelOptions(
            name='notification',
            options={'verbose_name': 'notification', 'verbose_name_plural': 'notifications'},
        ),
        migrations.AlterModelOptions(
            name='organization',
            options={'verbose_name': 'organization', 'verbose_name_plural': 'organizations'},
        ),
        migrations.AlterModelOptions(
            name='passwordreset',
            options={'verbose_name': 'Password reset request', 'verbose_name_plural': 'Password reset requests'},
        ),
        migrations.AlterModelOptions(
            name='person',
            options={'verbose_name': 'person', 'verbose_name_plural': 'people'},
        ),
        migrations.AlterModelOptions(
            name='position',
            options={'verbose_name': 'position', 'verbose_name_plural': 'positions'},
        ),
        migrations.AlterModelOptions(
            name='proposal',
            options={'get_latest_by': 'creation_date', 'verbose_name': 'issue', 'verbose_name_plural': 'issues'},
        ),
        migrations.AlterModelOptions(
            name='proposalversion',
            options={'verbose_name': 'issue version', 'verbose_name_plural': 'issue versions'},
        ),
        migrations.AlterModelOptions(
            name='proposalvote',
            options={'verbose_name': 'vote', 'verbose_name_plural': 'vote'},
        ),
        migrations.AlterModelOptions(
            name='publication',
            options={'verbose_name': 'publication', 'verbose_name_plural': 'publications'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'verbose_name': 'question', 'verbose_name_plural': 'questions'},
        ),
        migrations.AlterModelOptions(
            name='questioncomment',
            options={'verbose_name': 'comment', 'verbose_name_plural': 'comments'},
        ),
        migrations.AlterModelOptions(
            name='questionvote',
            options={'verbose_name': 'vote', 'verbose_name_plural': 'vote'},
        ),
        migrations.AlterModelOptions(
            name='reply',
            options={'verbose_name': 'reply', 'verbose_name_plural': 'replies'},
        ),
        migrations.AlterModelOptions(
            name='replycomment',
            options={'verbose_name': 'comment', 'verbose_name_plural': 'comments'},
        ),
        migrations.AlterModelOptions(
            name='replyvote',
            options={'verbose_name': 'vote', 'verbose_name_plural': 'vote'},
        ),
        migrations.AlterModelOptions(
            name='sector',
            options={'verbose_name': 'sector', 'verbose_name_plural': 'sectors'},
        ),
        migrations.AlterModelOptions(
            name='subscription',
            options={'verbose_name': 'subscription', 'verbose_name_plural': 'subscriptions'},
        ),
        migrations.AlterModelOptions(
            name='subscriptionid',
            options={'verbose_name': 'subscription id', 'verbose_name_plural': 'subscription ids'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': 'tag', 'verbose_name_plural': 'tags'},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'user profile', 'verbose_name_plural': 'user profiles'},
        ),
        migrations.AddField(
            model_name='proposal',
            name='language',
            field=models.CharField(default=b'en-ca', max_length=5, verbose_name='language', choices=[(b'en-ca', 'English'), (b'fr-ca', 'French')]),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='answer',
            name='creation_date',
            field=models.DateTimeField(verbose_name='creation date', editable=False),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='answer',
            name='last_modified',
            field=models.DateTimeField(verbose_name='last modified', editable=False),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='answer',
            name='score',
            field=models.SmallIntegerField(default=0, verbose_name='score', editable=False),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='answer',
            name='subscription_id',
            field=models.ForeignKey(editable=False, to='digidemo.SubscriptionId', verbose_name='subscription id'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='answer',
            name='target',
            field=models.ForeignKey(related_name='replies', verbose_name='target', to='digidemo.Question'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='answer',
            name='text',
            field=models.CharField(max_length=8192, verbose_name='text'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='answer',
            name='user',
            field=models.ForeignKey(verbose_name='user', to=settings.AUTH_USER_MODEL),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='answercomment',
            name='creation_date',
            field=models.DateTimeField(verbose_name='creation date', editable=False),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='answercomment',
            name='last_modified',
            field=models.DateTimeField(verbose_name='last modified', editable=False),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='answercomment',
            name='score',
            field=models.SmallIntegerField(default=0, verbose_name='score', editable=False),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='answercomment',
            name='subscription_id',
            field=models.ForeignKey(editable=False, to='digidemo.SubscriptionId', verbose_name='subscription id'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='answercomment',
            name='target',
            field=models.ForeignKey(related_name='comment_set', verbose_name='target', to='digidemo.Answer'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='answercomment',
            name='text',
            field=models.CharField(max_length=8192, verbose_name='text'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='answercomment',
            name='user',
            field=models.ForeignKey(verbose_name='user', to=settings.AUTH_USER_MODEL),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='answervote',
            name='creation_date',
            field=models.DateTimeField(verbose_name='creation date', editable=False),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='answervote',
            name='last_modified',
            field=models.DateTimeField(verbose_name='last modified', editable=False),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='answervote',
            name='target',
            field=models.ForeignKey(verbose_name='target', to='digidemo.Answer'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='answervote',
            name='user',
            field=models.ForeignKey(verbose_name='user', to=settings.AUTH_USER_MODEL),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='answervote',
            name='valence',
            field=models.SmallIntegerField(verbose_name='valence', choices=[(-1, b'down vote'), (0, b'non vote'), (1, b'up vote')]),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='comment',
            name='creation_date',
            field=models.DateTimeField(verbose_name='creation date', editable=False),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='comment',
            name='last_modified',
            field=models.DateTimeField(verbose_name='last modified', editable=False),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='comment',
            name='score',
            field=models.SmallIntegerField(default=0, verbose_name='score', editable=False),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='comment',
            name='subscription_id',
            field=models.ForeignKey(editable=False, to='digidemo.SubscriptionId', verbose_name='subscription id'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='comment',
            name='target',
            field=models.ForeignKey(related_name='comment_set', verbose_name='target', to='digidemo.Letter'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.CharField(max_length=8192, verbose_name='text'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(verbose_name='user', to=settings.AUTH_USER_MODEL),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='commentvote',
            name='creation_date',
            field=models.DateTimeField(verbose_name='creation date', editable=False),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='commentvote',
            name='last_modified',
            field=models.DateTimeField(verbose_name='last modified', editable=False),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='commentvote',
            name='target',
            field=models.ForeignKey(verbose_name='target', to='digidemo.Comment'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='commentvote',
            name='user',
            field=models.ForeignKey(verbose_name='user', to=settings.AUTH_USER_MODEL),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='commentvote',
            name='valence',
            field=models.SmallIntegerField(verbose_name='valence', choices=[(-1, b'down vote'), (0, b'non vote'), (1, b'up vote')]),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='discussion',
            name='creation_date',
            field=models.DateTimeField(verbose_name='creation date', editable=False),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='discussion',
            name='is_open',
            field=models.BooleanField(default=True, verbose_name='is open'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='discussion',
            name='last_modified',
            field=models.DateTimeField(verbose_name='last modified', editable=False),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='discussion',
            name='score',
            field=models.SmallIntegerField(default=0, verbose_name='score', editable=False),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='discussion',
            name='subscription_id',
            field=models.ForeignKey(editable=False, to='digidemo.SubscriptionId', verbose_name='subscription id'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='discussion',
            name='target',
            field=models.ForeignKey(verbose_name='target', to='digidemo.Proposal', null=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='discussion',
            name='text',
            field=models.CharField(max_length=8192, verbose_name='text'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='discussion',
            name='title',
            field=models.CharField(max_length=256, verbose_name='title'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='discussion',
            name='user',
            field=models.ForeignKey(verbose_name='user', to=settings.AUTH_USER_MODEL),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='discussioncomment',
            name='creation_date',
            field=models.DateTimeField(verbose_name='creation date', editable=False),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='discussioncomment',
            name='last_modified',
            field=models.DateTimeField(verbose_name='last modified', editable=False),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='discussioncomment',
            name='score',
            field=models.SmallIntegerField(default=0, verbose_name='score', editable=False),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='discussioncomment',
            name='subscription_id',
            field=models.ForeignKey(editable=False, to='digidemo.SubscriptionId', verbose_name='subscription id'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='discussioncomment',
            name='target',
            field=models.ForeignKey(related_name='comment_set', verbose_name='target', to='digidemo.Discussion'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='discussioncomment',
            name='text',
            field=models.CharField(max_length=8192, verbose_name='text'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='discussioncomment',
            name='user',
            field=models.ForeignKey(verbose_name='user', to=settings.AUTH_USER_MODEL),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='discussionvote',
            name='creation_date',
            field=models.DateTimeField(verbose_name='creation date', editable=False),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='discussionvote',
            name='last_modified',
            field=models.DateTimeField(verbose_name='last modified', editable=False),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='discussionvote',
            name='target',
            field=models.ForeignKey(verbose_name='target', to='digidemo.Discussion'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='discussionvote',
            name='user',
            field=models.ForeignKey(verbose_name='user', to=settings.AUTH_USER_MODEL),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='discussionvote',
            name='valence',
            field=models.SmallIntegerField(verbose_name='valence', choices=[(-1, b'down vote'), (0, b'non vote'), (1, b'up vote')]),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='emailrecipient',
            name='active',
            field=models.BooleanField(default=True, verbose_name='active'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='emailrecipient',
            name='creation_date',
            field=models.DateTimeField(verbose_name='creation date', editable=False),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='emailrecipient',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='email'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='emailrecipient',
            name='last_modified',
            field=models.DateTimeField(verbose_name='last modified', editable=False),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='emailverification',
            name='code',
            field=models.CharField(max_length=60, verbose_name='code'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='emailverification',
            name='creation_date',
            field=models.DateTimeField(verbose_name='creation date', editable=False),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='emailverification',
            name='last_modified',
            field=models.DateTimeField(verbose_name='last modified', editable=False),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='emailverification',
            name='user',
            field=models.ForeignKey(verbose_name='user', to=settings.AUTH_USER_MODEL),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='feedbacknote',
            name='creation_date',
            field=models.DateTimeField(verbose_name='creation date', editable=False),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='feedbacknote',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='email'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='feedbacknote',
            name='last_modified',
            field=models.DateTimeField(verbose_name='last modified', editable=False),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='feedbacknote',
            name='message',
            field=models.CharField(max_length=b'1024', verbose_name='message'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='letter',
            name='creation_date',
            field=models.DateTimeField(verbose_name='creation date', editable=False),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='letter',
            name='last_modified',
            field=models.DateTimeField(verbose_name='last modified', editable=False),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='letter',
            name='parent_letter',
            field=models.ForeignKey(related_name='resent_letters', verbose_name='parent letter', blank=True, to='digidemo.Letter', null=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='letter',
            name='recipients',
            field=models.ManyToManyField(related_name='letters', verbose_name='recipients', to='digidemo.Position'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='letter',
            name='score',
            field=models.SmallIntegerField(default=1, verbose_name='score'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='letter',
            name='subscription_id',
            field=models.ForeignKey(editable=False, to='digidemo.SubscriptionId', verbose_name='subscription id'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='letter',
            name='target',
            field=models.ForeignKey(verbose_name='target', to='digidemo.Proposal'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='letter',
            name='text',
            field=models.TextField(verbose_name='text'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='letter',
            name='title',
            field=models.CharField(max_length=256, verbose_name='title'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='letter',
            name='user',
            field=models.ForeignKey(verbose_name='user', to=settings.AUTH_USER_MODEL),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='letter',
            name='valence',
            field=models.SmallIntegerField(null=True, verbose_name='valence', choices=[(1, b'support'), (-1, b'oppose'), (0, b'ammend')]),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='lettervote',
            name='creation_date',
            field=models.DateTimeField(verbose_name='creation date', editable=False),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='lettervote',
            name='last_modified',
            field=models.DateTimeField(verbose_name='last modified', editable=False),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='lettervote',
            name='target',
            field=models.ForeignKey(verbose_name='target', to='digidemo.Letter'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='lettervote',
            name='user',
            field=models.ForeignKey(verbose_name='user', to=settings.AUTH_USER_MODEL),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='lettervote',
            name='valence',
            field=models.SmallIntegerField(verbose_name='valence', choices=[(-1, b'down vote'), (0, b'non vote'), (1, b'up vote')]),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='notification',
            name='creation_date',
            field=models.DateTimeField(verbose_name='creation date', editable=False),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='notification',
            name='event_data',
            field=models.CharField(max_length=2048, verbose_name='event data'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='notification',
            name='event_type',
            field=models.CharField(max_length=20, verbose_name='event type', choices=[(b'ISSUE', b'issue'), (b'EDIT_ISSUE', b'edit issue'), (b'QUESTION', b'question'), (b'ANSWER', b'answer'), (b'DISCUSSION', b'discussion'), (b'REPLY', b'reply'), (b'COMMENT', b'comment'), (b'LETTER', b'letter'), (b'SIGN_LETTER', b'sign letter'), (b'VOTE', b'vote'), (b'SYSTEM', b'system')]),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='notification',
            name='last_modified',
            field=models.DateTimeField(verbose_name='last modified', editable=False),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='notification',
            name='link_back',
            field=models.URLField(max_length=512, null=True, verbose_name='link back'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='notification',
            name='reason',
            field=models.CharField(max_length=20, verbose_name='reason', choices=[(b'AUTHOR', b'author'), (b'COMMENTER', b'commenter'), (b'SUBSCRIBED', b'actively subscribed'), (b'EDITOR', b'edited related content')]),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='notification',
            name='source_user',
            field=models.ForeignKey(related_name='triggered_notifications', verbose_name='source user', to=settings.AUTH_USER_MODEL, null=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='notification',
            name='target_user',
            field=models.ForeignKey(related_name='received_notifications', verbose_name='target user', to=settings.AUTH_USER_MODEL, null=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='notification',
            name='was_checked',
            field=models.BooleanField(default=False, verbose_name='was checked'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='notification',
            name='was_mailed',
            field=models.BooleanField(default=False, verbose_name='was mailed'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='notification',
            name='was_seen',
            field=models.BooleanField(default=False, verbose_name='was seen'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='organization',
            name='creation_date',
            field=models.DateTimeField(verbose_name='creation date', editable=False),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='organization',
            name='last_modified',
            field=models.DateTimeField(verbose_name='last modified', editable=False),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='organization',
            name='legal_classification',
            field=models.CharField(max_length=48, verbose_name='legal classification', choices=[(b'NP', b'non profit'), (b'NFP', b'not for profit'), (b'CH', b'charity'), (b'CPN', b'corporation'), (b'CRN', b'crown corporation'), (b'GVA', b'government agency'), (b'NPT', b'national political party'), (b'PPT', b'provincial political party'), (b'CTY', b'city / municipal administration'), (b'FND', b'foundation'), (b'COL', b'university or college'), (b'PRO', b'professional standards body'), (b'PRG', b'provincial regulatory association'), (b'NRG', b'national regulatory association'), (b'NGO', b'non-governmental organization'), (b'IG', b'industry group'), (b'LBU', b'labour union'), (b'OIG', b'other interest group')]),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='organization',
            name='legal_name',
            field=models.CharField(max_length=128, verbose_name='legal name'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='organization',
            name='operations_summary',
            field=models.TextField(verbose_name='operations summary'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='organization',
            name='revenue',
            field=models.BigIntegerField(verbose_name='revenue'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='organization',
            name='short_name',
            field=models.CharField(max_length=64, verbose_name='short name'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='passwordreset',
            name='creation_date',
            field=models.DateTimeField(verbose_name='creation date', editable=False),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='passwordreset',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='email'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='passwordreset',
            name='last_modified',
            field=models.DateTimeField(verbose_name='last modified', editable=False),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='passwordreset',
            name='username',
            field=models.CharField(max_length=8192, verbose_name='username'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='person',
            name='bio_summary',
            field=models.TextField(verbose_name='bio summary'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='person',
            name='creation_date',
            field=models.DateTimeField(verbose_name='creation date', editable=False),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='person',
            name='fname',
            field=models.CharField(max_length=48, verbose_name='first name'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='person',
            name='last_modified',
            field=models.DateTimeField(verbose_name='last modified', editable=False),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='person',
            name='lname',
            field=models.CharField(max_length=48, verbose_name='last name'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='person',
            name='portrait_url',
            field=models.CharField(max_length=256, verbose_name='portrait url'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='person',
            name='wikipedia_url',
            field=models.CharField(max_length=256, verbose_name='wikipedia url'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='position',
            name='creation_date',
            field=models.DateTimeField(verbose_name='creation date', editable=False),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='position',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='email'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='position',
            name='last_modified',
            field=models.DateTimeField(verbose_name='last modified', editable=False),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='position',
            name='mandate_summary',
            field=models.TextField(verbose_name='mandate summary'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='position',
            name='name',
            field=models.CharField(max_length=128, verbose_name='name'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='position',
            name='organization',
            field=models.ForeignKey(verbose_name='organization', to='digidemo.Organization'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='position',
            name='person',
            field=models.ForeignKey(verbose_name='person', to='digidemo.Person'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='position',
            name='salary',
            field=models.DecimalField(verbose_name='salary', max_digits=11, decimal_places=2),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='position',
            name='telephone',
            field=models.CharField(max_length=14, verbose_name='telephone'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='proposal',
            name='creation_date',
            field=models.DateTimeField(verbose_name='creation date', editable=False),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='proposal',
            name='is_published',
            field=models.BooleanField(default=False, verbose_name='is published'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='proposal',
            name='last_modified',
            field=models.DateTimeField(verbose_name='last modified', editable=False),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='proposal',
            name='original_user',
            field=models.ForeignKey(related_name='initiated_proposals', verbose_name='original author', to=settings.AUTH_USER_MODEL),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='proposal',
            name='proposal_image',
            field=models.ImageField(default=b'/digidemo/proposal-images/', upload_to=b'proposal_avatars', verbose_name='issue image'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='proposal',
            name='score',
            field=models.SmallIntegerField(default=0, verbose_name='score'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='proposal',
            name='sectors',
            field=models.ManyToManyField(related_name='proposals', null=True, verbose_name='sectors', to='digidemo.Sector', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='proposal',
            name='subscription_id',
            field=models.ForeignKey(editable=False, to='digidemo.SubscriptionId', verbose_name='subscription id'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='proposal',
            name='summary',
            field=models.TextField(verbose_name='summary'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='proposal',
            name='tags',
            field=models.ManyToManyField(related_name='proposals', null=True, verbose_name='tags', to='digidemo.Tag', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='proposal',
            name='text',
            field=models.TextField(verbose_name='text'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='proposal',
            name='title',
            field=models.CharField(max_length=256, verbose_name='title'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='proposal',
            name='user',
            field=models.ForeignKey(related_name='proposals_rectently_edited', verbose_name='last author', to=settings.AUTH_USER_MODEL),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='proposalversion',
            name='creation_date',
            field=models.DateTimeField(verbose_name='creation date', editable=False),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='proposalversion',
            name='last_modified',
            field=models.DateTimeField(verbose_name='last modified', editable=False),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='proposalversion',
            name='proposal',
            field=models.ForeignKey(verbose_name='issue', blank=True, to='digidemo.Proposal', null=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='proposalversion',
            name='sectors',
            field=models.ManyToManyField(related_name='proposal_versions', null=True, verbose_name='sectors', to='digidemo.Sector', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='proposalversion',
            name='summary',
            field=models.TextField(verbose_name='summary'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='proposalversion',
            name='tags',
            field=models.ManyToManyField(related_name='proposal_versions', null=True, verbose_name='tags', to='digidemo.Tag', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='proposalversion',
            name='text',
            field=models.TextField(verbose_name='text'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='proposalversion',
            name='title',
            field=models.CharField(max_length=256, verbose_name='title'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='proposalversion',
            name='user',
            field=models.ForeignKey(verbose_name='user', to=settings.AUTH_USER_MODEL),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='proposalvote',
            name='creation_date',
            field=models.DateTimeField(verbose_name='creation date', editable=False),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='proposalvote',
            name='last_modified',
            field=models.DateTimeField(verbose_name='last modified', editable=False),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='proposalvote',
            name='target',
            field=models.ForeignKey(verbose_name='target', to='digidemo.Proposal'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='proposalvote',
            name='user',
            field=models.ForeignKey(verbose_name='user', to=settings.AUTH_USER_MODEL),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='proposalvote',
            name='valence',
            field=models.SmallIntegerField(verbose_name='valence', choices=[(-1, b'down vote'), (0, b'non vote'), (1, b'up vote')]),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='publication',
            name='creation_date',
            field=models.DateTimeField(verbose_name='creation date', editable=False),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='publication',
            name='event_data',
            field=models.CharField(max_length=2048, verbose_name='event data'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='publication',
            name='event_type',
            field=models.CharField(max_length=20, verbose_name='event type', choices=[(b'ISSUE', b'issue'), (b'EDIT_ISSUE', b'edit issue'), (b'QUESTION', b'question'), (b'ANSWER', b'answer'), (b'DISCUSSION', b'discussion'), (b'REPLY', b'reply'), (b'COMMENT', b'comment'), (b'LETTER', b'letter'), (b'SIGN_LETTER', b'sign letter'), (b'VOTE', b'vote'), (b'SYSTEM', b'system')]),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='publication',
            name='last_modified',
            field=models.DateTimeField(verbose_name='last modified', editable=False),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='publication',
            name='link_back',
            field=models.URLField(max_length=512, null=True, verbose_name='link back'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='publication',
            name='source_user',
            field=models.ForeignKey(related_name='publications', verbose_name='source user', to=settings.AUTH_USER_MODEL, null=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='publication',
            name='subscription_id',
            field=models.ForeignKey(related_name='publications', verbose_name='subscription id', to='digidemo.SubscriptionId'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='publication',
            name='was_posted',
            field=models.BooleanField(default=False, verbose_name='was posted'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='question',
            name='creation_date',
            field=models.DateTimeField(verbose_name='creation date', editable=False),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='question',
            name='last_modified',
            field=models.DateTimeField(verbose_name='last modified', editable=False),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='question',
            name='score',
            field=models.SmallIntegerField(default=0, verbose_name='score', editable=False),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='question',
            name='subscription_id',
            field=models.ForeignKey(editable=False, to='digidemo.SubscriptionId', verbose_name='subscription id'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='question',
            name='target',
            field=models.ForeignKey(verbose_name='target', to='digidemo.Proposal'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.CharField(max_length=8192, verbose_name='text'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='question',
            name='title',
            field=models.CharField(max_length=256, verbose_name='title'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='question',
            name='user',
            field=models.ForeignKey(verbose_name='user', to=settings.AUTH_USER_MODEL),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='questioncomment',
            name='creation_date',
            field=models.DateTimeField(verbose_name='creation date', editable=False),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='questioncomment',
            name='last_modified',
            field=models.DateTimeField(verbose_name='last modified', editable=False),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='questioncomment',
            name='score',
            field=models.SmallIntegerField(default=0, verbose_name='score', editable=False),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='questioncomment',
            name='subscription_id',
            field=models.ForeignKey(editable=False, to='digidemo.SubscriptionId', verbose_name='subscription id'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='questioncomment',
            name='target',
            field=models.ForeignKey(related_name='comment_set', verbose_name='target', to='digidemo.Question'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='questioncomment',
            name='text',
            field=models.CharField(max_length=8192, verbose_name='text'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='questioncomment',
            name='user',
            field=models.ForeignKey(verbose_name='user', to=settings.AUTH_USER_MODEL),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='questionvote',
            name='creation_date',
            field=models.DateTimeField(verbose_name='creation date', editable=False),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='questionvote',
            name='last_modified',
            field=models.DateTimeField(verbose_name='last modified', editable=False),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='questionvote',
            name='target',
            field=models.ForeignKey(verbose_name='target', to='digidemo.Question'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='questionvote',
            name='user',
            field=models.ForeignKey(verbose_name='user', to=settings.AUTH_USER_MODEL),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='questionvote',
            name='valence',
            field=models.SmallIntegerField(verbose_name='valence', choices=[(-1, b'down vote'), (0, b'non vote'), (1, b'up vote')]),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='reply',
            name='creation_date',
            field=models.DateTimeField(verbose_name='creation date', editable=False),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='reply',
            name='is_open',
            field=models.BooleanField(default=False, verbose_name='is open'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='reply',
            name='last_modified',
            field=models.DateTimeField(verbose_name='last modified', editable=False),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='reply',
            name='score',
            field=models.SmallIntegerField(default=0, verbose_name='score', editable=False),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='reply',
            name='subscription_id',
            field=models.ForeignKey(editable=False, to='digidemo.SubscriptionId', verbose_name='subscription id'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='reply',
            name='target',
            field=models.ForeignKey(related_name='replies', verbose_name='target', to='digidemo.Discussion', null=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='reply',
            name='text',
            field=models.CharField(max_length=8192, verbose_name='text'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='reply',
            name='user',
            field=models.ForeignKey(verbose_name='user', to=settings.AUTH_USER_MODEL),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='replycomment',
            name='creation_date',
            field=models.DateTimeField(verbose_name='creation date', editable=False),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='replycomment',
            name='last_modified',
            field=models.DateTimeField(verbose_name='last modified', editable=False),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='replycomment',
            name='score',
            field=models.SmallIntegerField(default=0, verbose_name='score', editable=False),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='replycomment',
            name='subscription_id',
            field=models.ForeignKey(editable=False, to='digidemo.SubscriptionId', verbose_name='subscription id'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='replycomment',
            name='target',
            field=models.ForeignKey(related_name='comment_set', verbose_name='target', to='digidemo.Reply'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='replycomment',
            name='text',
            field=models.CharField(max_length=8192, verbose_name='text'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='replycomment',
            name='user',
            field=models.ForeignKey(verbose_name='user', to=settings.AUTH_USER_MODEL),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='replyvote',
            name='creation_date',
            field=models.DateTimeField(verbose_name='creation date', editable=False),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='replyvote',
            name='last_modified',
            field=models.DateTimeField(verbose_name='last modified', editable=False),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='replyvote',
            name='target',
            field=models.ForeignKey(verbose_name='target', to='digidemo.Reply'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='replyvote',
            name='user',
            field=models.ForeignKey(verbose_name='user', to=settings.AUTH_USER_MODEL),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='replyvote',
            name='valence',
            field=models.SmallIntegerField(verbose_name='valence', choices=[(-1, b'down vote'), (0, b'non vote'), (1, b'up vote')]),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='sector',
            name='creation_date',
            field=models.DateTimeField(verbose_name='creation date', editable=False),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='sector',
            name='last_modified',
            field=models.DateTimeField(verbose_name='last modified', editable=False),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='sector',
            name='name',
            field=models.CharField(max_length=64, verbose_name='name'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='sector',
            name='short_name',
            field=models.CharField(max_length=3, verbose_name='short name'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='sector',
            name='subscription_id',
            field=models.ForeignKey(editable=False, to='digidemo.SubscriptionId', verbose_name='subscription id'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='subscription',
            name='creation_date',
            field=models.DateTimeField(verbose_name='creation date', editable=False),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='subscription',
            name='last_modified',
            field=models.DateTimeField(verbose_name='last modified', editable=False),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='subscription',
            name='reason',
            field=models.CharField(max_length=20, verbose_name='reason', choices=[(b'AUTHOR', b'author'), (b'COMMENTER', b'commenter'), (b'SUBSCRIBED', b'actively subscribed'), (b'EDITOR', b'edited related content')]),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='subscription',
            name='subscription_id',
            field=models.ForeignKey(related_name='subscriptions', verbose_name='subscription id', to='digidemo.SubscriptionId'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='subscription',
            name='user',
            field=models.ForeignKey(related_name='subscriptions', verbose_name='user', to=settings.AUTH_USER_MODEL),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='subscriptionid',
            name='creation_date',
            field=models.DateTimeField(verbose_name='creation date', editable=False),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='subscriptionid',
            name='last_modified',
            field=models.DateTimeField(verbose_name='last modified', editable=False),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='subscriptionid',
            name='subscription_id',
            field=models.AutoField(serialize=False, verbose_name='subscription id', primary_key=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='tag',
            name='creation_date',
            field=models.DateTimeField(verbose_name='creation date', editable=False),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='tag',
            name='last_modified',
            field=models.DateTimeField(verbose_name='last modified', editable=False),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=48, verbose_name='name'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='tag',
            name='sector',
            field=models.ForeignKey(verbose_name=b'sector', to='digidemo.Sector', null=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='tag',
            name='subscription_id',
            field=models.ForeignKey(editable=False, to='digidemo.SubscriptionId', verbose_name='subscription id'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='tag',
            name='target',
            field=models.ForeignKey(verbose_name=b'target', to='digidemo.Tag', null=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='avatar_img',
            field=models.ImageField(upload_to=b'avatars', verbose_name='avatar image'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='country',
            field=models.CharField(max_length=64, verbose_name='country', choices=[(b'ABW', b'Aruba'), (b'AFG', b'Afghanistan'), (b'AGO', b'Angola'), (b'AIA', b'Anguilla'), (b'ALA', b'\xc3\x85land Islands'), (b'ALB', b'Albania'), (b'AND', b'Andorra'), (b'ARE', b'United Arab Emirates'), (b'ARG', b'Argentina'), (b'ARM', b'Armenia'), (b'ASM', b'American Samoa'), (b'ATA', b'Antarctica'), (b'ATF', b'French Southern Territories'), (b'ATG', b'Antigua and Barbuda'), (b'AUS', b'Australia'), (b'AUT', b'Austria'), (b'AZE', b'Azerbaijan'), (b'BDI', b'Burundi'), (b'BEL', b'Belgium'), (b'BEN', b'Benin'), (b'BES', b'Bonaire, Sint Eustatius and Saba'), (b'BFA', b'Burkina Faso'), (b'BGD', b'Bangladesh'), (b'BGR', b'Bulgaria'), (b'BHR', b'Bahrain'), (b'BHS', b'Bahamas'), (b'BIH', b'Bosnia and Herzegovina'), (b'BLM', b'Saint Barth\xc3\xa9lemy'), (b'BLR', b'Belarus'), (b'BLZ', b'Belize'), (b'BMU', b'Bermuda'), (b'BOL', b'Bolivia, Plurinational State of'), (b'BRA', b'Brazil'), (b'BRB', b'Barbados'), (b'BRN', b'Brunei Darussalam'), (b'BTN', b'Bhutan'), (b'BVT', b'Bouvet Island'), (b'BWA', b'Botswana'), (b'CAF', b'Central African Republic'), (b'CAN', b'Canada'), (b'CCK', b'Cocos (Keeling) Islands'), (b'CHE', b'Switzerland'), (b'CHL', b'Chile'), (b'CHN', b'China'), (b'CIV', b"C\xc3\xb4te d'Ivoire"), (b'CMR', b'Cameroon'), (b'COD', b'Congo, the Democratic Republic of the'), (b'COG', b'Congo'), (b'COK', b'Cook Islands'), (b'COL', b'Colombia'), (b'COM', b'Comoros'), (b'CPV', b'Cabo Verde'), (b'CRI', b'Costa Rica'), (b'CUB', b'Cuba'), (b'CUW', b'Cura\xc3\xa7ao'), (b'CXR', b'Christmas Island'), (b'CYM', b'Cayman Islands'), (b'CYP', b'Cyprus'), (b'CZE', b'Czech Republic'), (b'DEU', b'Germany'), (b'DJI', b'Djibouti'), (b'DMA', b'Dominica'), (b'DNK', b'Denmark'), (b'DOM', b'Dominican Republic'), (b'DZA', b'Algeria'), (b'ECU', b'Ecuador'), (b'EGY', b'Egypt'), (b'ERI', b'Eritrea'), (b'ESH', b'Western Sahara'), (b'ESP', b'Spain'), (b'EST', b'Estonia'), (b'ETH', b'Ethiopia'), (b'FIN', b'Finland'), (b'FJI', b'Fiji'), (b'FLK', b'Falkland Islands (Malvinas)'), (b'FRA', b'France'), (b'FRO', b'Faroe Islands'), (b'FSM', b'Micronesia, Federated States of'), (b'GAB', b'Gabon'), (b'GBR', b'United Kingdom'), (b'GEO', b'Georgia'), (b'GGY', b'Guernsey'), (b'GHA', b'Ghana'), (b'GIB', b'Gibraltar'), (b'GIN', b'Guinea'), (b'GLP', b'Guadeloupe'), (b'GMB', b'Gambia'), (b'GNB', b'Guinea-Bissau'), (b'GNQ', b'Equatorial Guinea'), (b'GRC', b'Greece'), (b'GRD', b'Grenada'), (b'GRL', b'Greenland'), (b'GTM', b'Guatemala'), (b'GUF', b'French Guiana'), (b'GUM', b'Guam'), (b'GUY', b'Guyana'), (b'HKG', b'Hong Kong'), (b'HMD', b'Heard Island and McDonald Islands'), (b'HND', b'Honduras'), (b'HRV', b'Croatia'), (b'HTI', b'Haiti'), (b'HUN', b'Hungary'), (b'IDN', b'Indonesia'), (b'IMN', b'Isle of Man'), (b'IND', b'India'), (b'IOT', b'British Indian Ocean Territory'), (b'IRL', b'Ireland'), (b'IRN', b'Iran, Islamic Republic of'), (b'IRQ', b'Iraq'), (b'ISL', b'Iceland'), (b'ISR', b'Israel'), (b'ITA', b'Italy'), (b'JAM', b'Jamaica'), (b'JEY', b'Jersey'), (b'JOR', b'Jordan'), (b'JPN', b'Japan'), (b'KAZ', b'Kazakhstan'), (b'KEN', b'Kenya'), (b'KGZ', b'Kyrgyzstan'), (b'KHM', b'Cambodia'), (b'KIR', b'Kiribati'), (b'KNA', b'Saint Kitts and Nevis'), (b'KOR', b'Korea, Republic of'), (b'KWT', b'Kuwait'), (b'LAO', b"Lao People's Democratic Republic"), (b'LBN', b'Lebanon'), (b'LBR', b'Liberia'), (b'LBY', b'Libya'), (b'LCA', b'Saint Lucia'), (b'LIE', b'Liechtenstein'), (b'LKA', b'Sri Lanka'), (b'LSO', b'Lesotho'), (b'LTU', b'Lithuania'), (b'LUX', b'Luxembourg'), (b'LVA', b'Latvia'), (b'MAC', b'Macao'), (b'MAF', b'Saint Martin (French part)'), (b'MAR', b'Morocco'), (b'MCO', b'Monaco'), (b'MDA', b'Moldova, Republic of'), (b'MDG', b'Madagascar'), (b'MDV', b'Maldives'), (b'MEX', b'Mexico'), (b'MHL', b'Marshall Islands'), (b'MKD', b'Macedonia, the former Yugoslav Republic of'), (b'MLI', b'Mali'), (b'MLT', b'Malta'), (b'MMR', b'Myanmar'), (b'MNE', b'Montenegro'), (b'MNG', b'Mongolia'), (b'MNP', b'Northern Mariana Islands'), (b'MOZ', b'Mozambique'), (b'MRT', b'Mauritania'), (b'MSR', b'Montserrat'), (b'MTQ', b'Martinique'), (b'MUS', b'Mauritius'), (b'MWI', b'Malawi'), (b'MYS', b'Malaysia'), (b'MYT', b'Mayotte'), (b'NAM', b'Namibia'), (b'NCL', b'New Caledonia'), (b'NER', b'Niger'), (b'NFK', b'Norfolk Island'), (b'NGA', b'Nigeria'), (b'NIC', b'Nicaragua'), (b'NIU', b'Niue'), (b'NLD', b'Netherlands'), (b'NOR', b'Norway'), (b'NPL', b'Nepal'), (b'NRU', b'Nauru'), (b'NZL', b'New Zealand'), (b'OMN', b'Oman'), (b'PAK', b'Pakistan'), (b'PAN', b'Panama'), (b'PCN', b'Pitcairn'), (b'PER', b'Peru'), (b'PHL', b'Philippines'), (b'PLW', b'Palau'), (b'PNG', b'Papua New Guinea'), (b'POL', b'Poland'), (b'PRI', b'Puerto Rico'), (b'PRK', b"Korea, Democratic People's Republic of"), (b'PRT', b'Portugal'), (b'PRY', b'Paraguay'), (b'PSE', b'Palestine, State of'), (b'PYF', b'French Polynesia'), (b'QAT', b'Qatar'), (b'REU', b'R\xc3\xa9union'), (b'ROU', b'Romania'), (b'RUS', b'Russian Federation'), (b'RWA', b'Rwanda'), (b'SAU', b'Saudi Arabia'), (b'SDN', b'Sudan'), (b'SEN', b'Senegal'), (b'SGP', b'Singapore'), (b'SGS', b'South Georgia and the South Sandwich Islands'), (b'SHN', b'Saint Helena, Ascension and Tristan da Cunha'), (b'SJM', b'Svalbard and Jan Mayen'), (b'SLB', b'Solomon Islands'), (b'SLE', b'Sierra Leone'), (b'SLV', b'El Salvador'), (b'SMR', b'San Marino'), (b'SOM', b'Somalia'), (b'SPM', b'Saint Pierre and Miquelon'), (b'SRB', b'Serbia'), (b'SSD', b'South Sudan'), (b'STP', b'Sao Tome and Principe'), (b'SUR', b'Suriname'), (b'SVK', b'Slovakia'), (b'SVN', b'Slovenia'), (b'SWE', b'Sweden'), (b'SWZ', b'Swaziland'), (b'SXM', b'Sint Maarten (Dutch part)'), (b'SYC', b'Seychelles'), (b'SYR', b'Syrian Arab Republic'), (b'TCA', b'Turks and Caicos Islands'), (b'TCD', b'Chad'), (b'TGO', b'Togo'), (b'THA', b'Thailand'), (b'TJK', b'Tajikistan'), (b'TKL', b'Tokelau'), (b'TKM', b'Turkmenistan'), (b'TLS', b'Timor-Leste'), (b'TON', b'Tonga'), (b'TTO', b'Trinidad and Tobago'), (b'TUN', b'Tunisia'), (b'TUR', b'Turkey'), (b'TUV', b'Tuvalu'), (b'TWN', b'Taiwan, Province of China'), (b'TZA', b'Tanzania, United Republic of'), (b'UGA', b'Uganda'), (b'UKR', b'Ukraine'), (b'UMI', b'United States Minor Outlying Islands'), (b'URY', b'Uruguay'), (b'USA', b'United States'), (b'UZB', b'Uzbekistan'), (b'VAT', b'Holy See (Vatican City State)'), (b'VCT', b'Saint Vincent and the Grenadines'), (b'VEN', b'Venezuela, Bolivarian Republic of'), (b'VGB', b'Virgin Islands, British'), (b'VIR', b'Virgin Islands, U.S.'), (b'VNM', b'Viet Nam'), (b'VUT', b'Vanuatu'), (b'WLF', b'Wallis and Futuna'), (b'WSM', b'Samoa'), (b'YEM', b'Yemen'), (b'ZAF', b'South Africa'), (b'ZMB', b'Zambia'), (b'ZWE', b'Zimbabwe')]),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='creation_date',
            field=models.DateTimeField(verbose_name='creation date', editable=False),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='do_email_news',
            field=models.BooleanField(default=True, verbose_name='do email news'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='do_email_petitions',
            field=models.BooleanField(default=True, verbose_name='do email petitions'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='do_email_responses',
            field=models.BooleanField(default=True, verbose_name='do email responses'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='do_email_watched',
            field=models.BooleanField(default=True, verbose_name='do email watched'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='email_validated',
            field=models.BooleanField(default=False, verbose_name='email validated'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='last_modified',
            field=models.DateTimeField(verbose_name='last modified', editable=False),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='province',
            field=models.CharField(blank=True, max_length=32, verbose_name='province', choices=[(b'AB', b'Alberta'), (b'BC', b'British Columbia'), (b'MB', b'Manitoba'), (b'SK', b'Saskatchewan'), (b'PE', b'Prince Edward Island'), (b'QC', b'Quebec'), (b'NL', b'Newfoundland and Labrador'), (b'NU', b'Nunavut'), (b'YT', b'Yukon'), (b'NS', b'Nova Scotia'), (b'NB', b'New Brunswick'), (b'NT', b'Northwest Territories'), (b'ON', b'Ontario')]),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='rep',
            field=models.IntegerField(default=0, verbose_name='reputation'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='street',
            field=models.CharField(max_length=128, verbose_name='street'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(related_name='profile', verbose_name='user', to=settings.AUTH_USER_MODEL),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='zip_code',
            field=models.CharField(max_length=10, verbose_name='zip_code'),
            preserve_default=True,
        ),
    ]
